import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { ROOT } from "@/lib/answers";
import { admit } from "@/lib/ratelimit";
import { redact } from "@/lib/redact";

/** Runs the real Python agent. Requires the project's .venv, so this works in local
 *  development and anywhere the Python environment is present. The preset answers on
 *  the landing page are pre-generated by the same code path, so the deployed page
 *  still shows genuine pipeline output when Python is not available.
 *
 *  The response is an event stream, not one JSON body. A run takes about two minutes, measured,
 *  and the agent writes each reasoning step to stderr as `@progress {json}` the moment it
 *  happens. Forwarding those lets the interface show the loop working rather than a dead
 *  button for that whole time. The final event carries the answer.
 *
 *  The server keeps nothing. The agent needs a file to write its result to, so it gets a temp
 *  directory that is removed as soon as the answer has been read out to the caller; whoever asked
 *  is the only one who ends up holding the run, in their own browser. A restart therefore loses
 *  no history that was ever the server's to lose, which on a diskless free instance is the
 *  honest arrangement rather than a lesser one. */

export const maxDuration = 300;

const PYTHON = join(ROOT, ".venv", "bin", "python");
const SCRIPT = join(ROOT, "scripts", "ask.py");

const PROGRESS_PREFIX = "@progress ";

export async function POST(request: Request) {
  let question = "";
  try {
    ({ question } = await request.json());
  } catch {
    return Response.json({ error: "invalid JSON body" }, { status: 400 });
  }

  question = (question ?? "").trim();
  if (!question) return Response.json({ error: "question is required" }, { status: 400 });
  if (question.length > 400) {
    return Response.json({ error: "question too long" }, { status: 400 });
  }

  // Checked after validation, so a malformed request never spends part of someone's quota.
  const admission = admit(request);
  if (!admission.ok) {
    return Response.json(
      { error: admission.error },
      { status: admission.status, headers: { "retry-after": String(admission.retryAfter) } },
    );
  }

  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const send = (event: string, data: unknown) => {
        controller.enqueue(encoder.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`));
      };

      // Retrieval and synthesis are the two long silences in a run, and a proxy in front of the
      // server reads silence as a dead connection. Locally nothing sits in front, so this only
      // matters once deployed, which is exactly when it is hard to debug. A line starting with
      // `:` is an SSE comment: it keeps bytes flowing and the client ignores it.
      const heartbeat = setInterval(() => {
        try {
          controller.enqueue(encoder.encode(": keepalive\n\n"));
        } catch {
          // The stream is already closed; the interval is cleared in `finally`.
        }
      }, 15_000);

      // Somewhere for the agent to write, and nowhere else. Removed in the `finally` below,
      // whether or not the run got that far.
      const scratch = await mkdtemp(join(tmpdir(), "ephemeris-"));
      const outPath = join(scratch, "answer.json");

      try {
        // The question is passed as a separate argv entry, never interpolated into a
        // shell string, and no shell is spawned.
        //
        // `-P` keeps the script's own directory off sys.path. Without it `scripts/select.py`
        // shadows the stdlib `select`, and `subprocess` fails partway through its import, which
        // takes the run down before it reaches VideoDB. It does not reproduce everywhere: where
        // `select` is compiled into the interpreter it wins regardless, and where it ships as a
        // dynamic extension the sibling file wins instead. `ask.py` puts `src/` on the path
        // itself and imports nothing from `scripts/`, so losing that entry costs it nothing.
        const child = spawn(PYTHON, ["-P", SCRIPT, question, "--json", outPath], {
          cwd: ROOT,
          stdio: ["ignore", "ignore", "pipe"],
        });

        let errors = "";
        let pending = "";

        child.stderr.on("data", (chunk) => {
          pending += String(chunk);
          const lines = pending.split("\n");
          // Keep the trailing fragment: a write can split mid-line.
          pending = lines.pop() ?? "";
          for (const line of lines) {
            if (line.startsWith(PROGRESS_PREFIX)) {
              try {
                send("progress", JSON.parse(line.slice(PROGRESS_PREFIX.length)));
              } catch {
                // A malformed progress line is not worth failing a run over.
              }
            } else if (line.trim()) {
              errors += `${line}\n`;
            }
          }
        });

        const exit = await new Promise<number>((done, fail) => {
          child.on("error", fail);
          child.on("close", (code) => done(code ?? 0));
        });

        if (exit !== 0) {
          throw new Error(errors.trim().slice(-1200) || `agent exited ${exit}`);
        }

        // The only copy that outlives this request is the one the client is about to keep.
        send("result", JSON.parse(await readFile(outPath, "utf8")));
      } catch (error) {
        const raw = error instanceof Error ? error.message : String(error);
        // The unredacted text stays on the server, where the host's log is the right place for
        // absolute paths. What is sent below is public.
        console.error("[ask] run failed:", raw);
        send("error", { error: redact(raw) });
      } finally {
        admission.release();
        clearInterval(heartbeat);
        await rm(scratch, { recursive: true, force: true });
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "content-type": "text/event-stream; charset=utf-8",
      "cache-control": "no-cache, no-transform",
      connection: "keep-alive",
    },
  });
}
