import { spawn } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { ANSWERS_DIR, ROOT, answerId } from "@/lib/answers";
import { admit } from "@/lib/ratelimit";
import { redact } from "@/lib/redact";

/** Runs the real Python agent. Requires the project's .venv, so this works in local
 *  development and anywhere the Python environment is present. The preset answers on
 *  the landing page are pre-generated by the same code path, so the deployed page
 *  still shows genuine pipeline output when Python is not available.
 *
 *  The response is an event stream, not one JSON body. A run takes about two minutes, measured,
 *  and the agent writes each reasoning step to stderr as `@progress {json}` the moment it
 *  happens. Forwarding those lets the interface show the loop working rather than a dead
 *  button for that whole time. The final event carries the answer. */

export const maxDuration = 300;

const PYTHON = join(ROOT, ".venv", "bin", "python");
const SCRIPT = join(ROOT, "scripts", "ask.py");

const PROGRESS_PREFIX = "@progress ";

/** Keep the question when the run did not survive to produce an answer.
 *
 *  Shaped like any other saved run so the list and the reload route need no special case: the
 *  answer is empty and the caveat says what went wrong, which is how a refusal already reads. */
async function recordFailure(outPath: string, question: string, detail: string): Promise<void> {
  try {
    await readFile(outPath, "utf8");
    return; // the agent wrote its own result; the failure was ours, downstream of it
  } catch {
    // nothing there, so there is something worth writing
  }
  const stub = {
    question,
    plan: { sub_questions: [], phrasings: [], visual_phrasings: [],
            needs_chronology: false, answerable: false, target_body: null,
            rationale: "the run did not complete" },
    answer: { answer: "", citations: [], chronology: [],
              caveats: `This run did not complete: ${detail.slice(-400)}` },
    evidence: [],
    rejected: { below_threshold: [], diversity: [],
                counts: { below_threshold: 0, diversity: 0 } },
    timeline: [],
    trace: [],
    failed: true,
  };
  try {
    await writeFile(outPath, JSON.stringify(stub, null, 2));
  } catch {
    // Losing the record of a failure is not worth reporting a second failure over.
  }
}

export async function POST(request: Request) {
  let question = "";
  try {
    ({ question } = await request.json());
  } catch {
    return Response.json({ error: "invalid JSON body" }, { status: 400 });
  }

  question = (question ?? "").trim();
  if (!question) return Response.json({ error: "question is required" }, { status: 400 });
  if (question.length > 400) {
    return Response.json({ error: "question too long" }, { status: 400 });
  }

  // Checked after validation, so a malformed request never spends part of someone's quota.
  const admission = admit(request);
  if (!admission.ok) {
    return Response.json(
      { error: admission.error },
      { status: admission.status, headers: { "retry-after": String(admission.retryAfter) } },
    );
  }

  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const send = (event: string, data: unknown) => {
        controller.enqueue(encoder.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`));
      };

      // Retrieval and synthesis are the two long silences in a run, and a proxy in front of the
      // server reads silence as a dead connection. Locally nothing sits in front, so this only
      // matters once deployed, which is exactly when it is hard to debug. A line starting with
      // `:` is an SSE comment: it keeps bytes flowing and the client ignores it.
      const heartbeat = setInterval(() => {
        try {
          controller.enqueue(encoder.encode(": keepalive\n\n"));
        } catch {
          // The stream is already closed; the interval is cleared in `finally`.
        }
      }, 15_000);

      // The agent writes its result straight into data/answers, alongside the presets, and it
      // stays there. If that directory cannot be created the run still happens: persistence is
      // worth having, not worth failing a two-minute run over.
      const id = answerId(question, new Date());
      let outPath: string;
      let scratch: string | null = null;
      try {
        await mkdir(ANSWERS_DIR, { recursive: true });
        outPath = join(ANSWERS_DIR, `${id}.json`);
      } catch {
        scratch = await mkdtemp(join(tmpdir(), "ephemeris-"));
        outPath = join(scratch, "answer.json");
      }

      try {
        // The question is passed as a separate argv entry, never interpolated into a
        // shell string, and no shell is spawned.
        //
        // `-P` keeps the script's own directory off sys.path. Without it `scripts/select.py`
        // shadows the stdlib `select`, and `subprocess` fails partway through its import, which
        // takes the run down before it reaches VideoDB. It does not reproduce everywhere: where
        // `select` is compiled into the interpreter it wins regardless, and where it ships as a
        // dynamic extension the sibling file wins instead. `ask.py` puts `src/` on the path
        // itself and imports nothing from `scripts/`, so losing that entry costs it nothing.
        const child = spawn(PYTHON, ["-P", SCRIPT, question, "--json", outPath], {
          cwd: ROOT,
          stdio: ["ignore", "ignore", "pipe"],
        });

        let errors = "";
        let pending = "";

        child.stderr.on("data", (chunk) => {
          pending += String(chunk);
          const lines = pending.split("\n");
          // Keep the trailing fragment: a write can split mid-line.
          pending = lines.pop() ?? "";
          for (const line of lines) {
            if (line.startsWith(PROGRESS_PREFIX)) {
              try {
                send("progress", JSON.parse(line.slice(PROGRESS_PREFIX.length)));
              } catch {
                // A malformed progress line is not worth failing a run over.
              }
            } else if (line.trim()) {
              errors += `${line}\n`;
            }
          }
        });

        const exit = await new Promise<number>((done, fail) => {
          child.on("error", fail);
          child.on("close", (code) => done(code ?? 0));
        });

        if (exit !== 0) {
          throw new Error(errors.trim().slice(-1200) || `agent exited ${exit}`);
        }

        const result = JSON.parse(await readFile(outPath, "utf8"));
        // The id travels with the answer so the interface can name the file it was saved to,
        // and reload it later without re-running the agent.
        send("result", scratch ? result : { ...result, saved_id: id });
      } catch (error) {
        const raw = error instanceof Error ? error.message : String(error);
        // The unredacted text stays on the server, where the host's log is the right place for
        // absolute paths. Everything below this line is public: the browser gets it, and a
        // recorded failure is served by `/api/answers/[id]` to whoever asks.
        console.error("[ask] run failed:", raw);
        const detail = redact(raw);
        // A run that fails still asked a question, and that question is the part worth keeping:
        // without this the agent crashing loses what was typed, which is exactly when someone
        // most wants it back. Written only if the agent left nothing itself, so a real result
        // is never overwritten by a failure to read it.
        if (!scratch) await recordFailure(outPath, question, detail);
        send("error", { error: detail });
      } finally {
        admission.release();
        clearInterval(heartbeat);
        // Only the fallback scratch directory is cleaned up. A saved answer is the point.
        if (scratch) await rm(scratch, { recursive: true, force: true });
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "content-type": "text/event-stream; charset=utf-8",
      "cache-control": "no-cache, no-transform",
      connection: "keep-alive",
    },
  });
}
